[package]
name = "lab_grader"
version = "0.1.0"
authors = ["llamicron <llamicron@gmail.com>"]
edition = "2018"
description = "A crate to help grade labs and assignments"
documentation = "https://docs.rs/crate/lab_grader"
readme = "README.md"
homepage = "https://github.com/llamicron/lab_grader"
repository = "https://github.com/llamicron/lab_grader"
license = "MIT"
keywords = [ "grade", "academia", "automation", ]
categories = [ "command-line-utilities", ]

[dependencies]


[dev-dependencies]
tempdir = "0.3"
pretty_assertions = "0.6"
