name: Build Book

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./book

    steps:
    - uses: actions/checkout@v2
    - name: Install mdbook
      run: cargo install mdbook
    - name: Build book
      run: mdbook build -d ../docs
      working-directory: ${{env.working-directory}}

