name: Testing Suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust Nightly
      run: rustup default nightly
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --verbose

