name: Testing Suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]


    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust Nightly
      run: rustup default nightly

    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test --verbose

    - name: Run ignored tests
      run: cargo test -- --ignored

